vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        user_pictures:
            uri_prefix: /uploads/images/user_pictures
            upload_destination: '%kernel.project_dir%/public/uploads/images/user_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

        child_pictures:
            uri_prefix: /uploads/images/child_pictures
            upload_destination: '%kernel.project_dir%/public/uploads/images/child_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true

        # event_pictures:
        #     uri_prefix: /uploads/images/event_pictures
        #     upload_destination: '%kernel.project_dir%/public/uploads/images/event_pictures'
        #     namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        #     delete_on_remove: true
        #     delete_on_update: true